# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pr:
- main

pool:
  vmImage: ubuntu-latest

resources:
  containers:
    - container: ubuntu-custom
      image: mattgomes28/cpp-ubuntu-bionic:0.7

stages:
- stage: build
  displayName: Build Stage
  jobs:
  - job: build_ubuntu_x86_64
    container: ubuntu-custom
    displayName: Ubuntu 24.04 Build
    continueOnError: false
    steps:
      # - bash: |
      #     set -euo pipefail
      #     scripts/build_x86_64.sh unix-rel
      #     mkdir -p "$(Build.SourcesDirectory)/artifacts"
      #     tar -zcf "$(Build.SourcesDirectory)/artifacts/build.tar.gz" "build"
      #   displayName: Cmake Build & Package
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: "$(Build.SourcesDirectory)"
          artifactName: UbuntuRelBuild
      - task: CMake@1
        inputs:
          cmakeArgs: --build . --config Debug
